// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ManagementMeetingsTracker.Controllers
{
    public partial class MeetingItemController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MeetingItemController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MeetingItemController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> GetAddEditMeetingItem()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAddEditMeetingItem);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> GetMeetingItems()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMeetingItems);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SaveMeetingItem()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveMeetingItem);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MeetingItemController Actions { get { return MVC.MeetingItem; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "MeetingItem";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "MeetingItem";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string GetAddEditMeetingItem = "GetAddEditMeetingItem";
            public readonly string GetMeetingItems = "GetMeetingItems";
            public readonly string SaveMeetingItem = "SaveMeetingItem";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string GetAddEditMeetingItem = "GetAddEditMeetingItem";
            public const string GetMeetingItems = "GetMeetingItems";
            public const string SaveMeetingItem = "SaveMeetingItem";
        }


        static readonly ActionParamsClass_GetAddEditMeetingItem s_params_GetAddEditMeetingItem = new ActionParamsClass_GetAddEditMeetingItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAddEditMeetingItem GetAddEditMeetingItemParams { get { return s_params_GetAddEditMeetingItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAddEditMeetingItem
        {
            public readonly string MeetingId = "MeetingId";
            public readonly string MeetingItemId = "MeetingItemId";
        }
        static readonly ActionParamsClass_GetMeetingItems s_params_GetMeetingItems = new ActionParamsClass_GetMeetingItems();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetMeetingItems GetMeetingItemsParams { get { return s_params_GetMeetingItems; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetMeetingItems
        {
            public readonly string MeetingId = "MeetingId";
        }
        static readonly ActionParamsClass_SaveMeetingItem s_params_SaveMeetingItem = new ActionParamsClass_SaveMeetingItem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveMeetingItem SaveMeetingItemParams { get { return s_params_SaveMeetingItem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveMeetingItem
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
            static readonly _PartialClass s_Partial = new _PartialClass();
            public _PartialClass Partial { get { return s_Partial; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _GetAddMeetingItem = "_GetAddMeetingItem";
                    public readonly string _GetMeetingItems = "_GetMeetingItems";
                }
                public readonly string _GetAddMeetingItem = "~/Views/MeetingItem/Partial/_GetAddMeetingItem.cshtml";
                public readonly string _GetMeetingItems = "~/Views/MeetingItem/Partial/_GetMeetingItems.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MeetingItemController : ManagementMeetingsTracker.Controllers.MeetingItemController
    {
        public T4MVC_MeetingItemController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GetAddEditMeetingItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int MeetingId, int? MeetingItemId);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> GetAddEditMeetingItem(int MeetingId, int? MeetingItemId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAddEditMeetingItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "MeetingId", MeetingId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "MeetingItemId", MeetingItemId);
            GetAddEditMeetingItemOverride(callInfo, MeetingId, MeetingItemId);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

        [NonAction]
        partial void GetMeetingItemsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int MeetingId);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> GetMeetingItems(int MeetingId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetMeetingItems);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "MeetingId", MeetingId);
            GetMeetingItemsOverride(callInfo, MeetingId);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

        [NonAction]
        partial void SaveMeetingItemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ManagementMeetingsTracker.Models.MeetingItemModel model);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> SaveMeetingItem(ManagementMeetingsTracker.Models.MeetingItemModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SaveMeetingItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SaveMeetingItemOverride(callInfo, model);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.ActionResult);
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
