// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static ManagementMeetingsTracker.Controllers.HomeController Home = new ManagementMeetingsTracker.Controllers.T4MVC_HomeController();
    public static ManagementMeetingsTracker.Controllers.MeetingController Meeting = new ManagementMeetingsTracker.Controllers.T4MVC_MeetingController();
    public static ManagementMeetingsTracker.Controllers.MeetingItemController MeetingItem = new ManagementMeetingsTracker.Controllers.T4MVC_MeetingItemController();
    public static ManagementMeetingsTracker.Controllers.MeetingTypeController MeetingType = new ManagementMeetingsTracker.Controllers.T4MVC_MeetingTypeController();
    public static T4MVC.MeetingTypesController MeetingTypes = new T4MVC.MeetingTypesController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

#pragma warning disable 0436
namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_FileResult : System.Web.Mvc.FileResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_FileResult(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    protected override void WriteFile(System.Web.HttpResponseBase response) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bootbox_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootbox.min.js") ? Url("bootbox.min.js") : Url("bootbox.js");
        public static readonly string bootbox_min_js = Url("bootbox.min.js");
        public static readonly string bootstrap_datepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-datepicker.min.js") ? Url("bootstrap-datepicker.min.js") : Url("bootstrap-datepicker.js");
        public static readonly string bootstrap_datepicker_min_js = Url("bootstrap-datepicker.min.js");
        public static readonly string bootstrap_datetimepicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-datetimepicker.min.js") ? Url("bootstrap-datetimepicker.min.js") : Url("bootstrap-datetimepicker.js");
        public static readonly string bootstrap_datetimepicker_min_js = Url("bootstrap-datetimepicker.min.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string chosen_jquery_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/chosen.jquery.min.js") ? Url("chosen.jquery.min.js") : Url("chosen.jquery.js");
        public static readonly string chosen_jquery_min_js = Url("chosen.jquery.min.js");
        public static readonly string jquery_1_12_4_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.12.4-vsdoc.min.js") ? Url("jquery-1.12.4-vsdoc.min.js") : Url("jquery-1.12.4-vsdoc.js");
        public static readonly string jquery_1_12_4_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-1.12.4.min.js") ? Url("jquery-1.12.4.min.js") : Url("jquery-1.12.4.js");
        public static readonly string jquery_1_12_4_min_js = Url("jquery-1.12.4.min.js");
        public static readonly string jquery_1_12_4_min_map = Url("jquery-1.12.4.min.map");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class locales {
            public const string UrlPath = "~/Scripts/locales";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            public static readonly string bootstrap_datepicker_en_CA_min_js = Url("bootstrap-datepicker-en-CA.min.js");
            public static readonly string bootstrap_datepicker_ar_tn_min_js = Url("bootstrap-datepicker.ar-tn.min.js");
            public static readonly string bootstrap_datepicker_ar_min_js = Url("bootstrap-datepicker.ar.min.js");
            public static readonly string bootstrap_datepicker_az_min_js = Url("bootstrap-datepicker.az.min.js");
            public static readonly string bootstrap_datepicker_bg_min_js = Url("bootstrap-datepicker.bg.min.js");
            public static readonly string bootstrap_datepicker_bn_min_js = Url("bootstrap-datepicker.bn.min.js");
            public static readonly string bootstrap_datepicker_br_min_js = Url("bootstrap-datepicker.br.min.js");
            public static readonly string bootstrap_datepicker_bs_min_js = Url("bootstrap-datepicker.bs.min.js");
            public static readonly string bootstrap_datepicker_ca_min_js = Url("bootstrap-datepicker.ca.min.js");
            public static readonly string bootstrap_datepicker_cs_min_js = Url("bootstrap-datepicker.cs.min.js");
            public static readonly string bootstrap_datepicker_cy_min_js = Url("bootstrap-datepicker.cy.min.js");
            public static readonly string bootstrap_datepicker_da_min_js = Url("bootstrap-datepicker.da.min.js");
            public static readonly string bootstrap_datepicker_de_min_js = Url("bootstrap-datepicker.de.min.js");
            public static readonly string bootstrap_datepicker_el_min_js = Url("bootstrap-datepicker.el.min.js");
            public static readonly string bootstrap_datepicker_en_AU_min_js = Url("bootstrap-datepicker.en-AU.min.js");
            public static readonly string bootstrap_datepicker_en_CA_min_js_ = Url("bootstrap-datepicker.en-CA.min.js");
            public static readonly string bootstrap_datepicker_en_GB_min_js = Url("bootstrap-datepicker.en-GB.min.js");
            public static readonly string bootstrap_datepicker_en_IE_min_js = Url("bootstrap-datepicker.en-IE.min.js");
            public static readonly string bootstrap_datepicker_en_NZ_min_js = Url("bootstrap-datepicker.en-NZ.min.js");
            public static readonly string bootstrap_datepicker_en_ZA_min_js = Url("bootstrap-datepicker.en-ZA.min.js");
            public static readonly string bootstrap_datepicker_eo_min_js = Url("bootstrap-datepicker.eo.min.js");
            public static readonly string bootstrap_datepicker_es_min_js = Url("bootstrap-datepicker.es.min.js");
            public static readonly string bootstrap_datepicker_et_min_js = Url("bootstrap-datepicker.et.min.js");
            public static readonly string bootstrap_datepicker_eu_min_js = Url("bootstrap-datepicker.eu.min.js");
            public static readonly string bootstrap_datepicker_fa_min_js = Url("bootstrap-datepicker.fa.min.js");
            public static readonly string bootstrap_datepicker_fi_min_js = Url("bootstrap-datepicker.fi.min.js");
            public static readonly string bootstrap_datepicker_fo_min_js = Url("bootstrap-datepicker.fo.min.js");
            public static readonly string bootstrap_datepicker_fr_CH_min_js = Url("bootstrap-datepicker.fr-CH.min.js");
            public static readonly string bootstrap_datepicker_fr_min_js = Url("bootstrap-datepicker.fr.min.js");
            public static readonly string bootstrap_datepicker_gl_min_js = Url("bootstrap-datepicker.gl.min.js");
            public static readonly string bootstrap_datepicker_he_min_js = Url("bootstrap-datepicker.he.min.js");
            public static readonly string bootstrap_datepicker_hi_min_js = Url("bootstrap-datepicker.hi.min.js");
            public static readonly string bootstrap_datepicker_hr_min_js = Url("bootstrap-datepicker.hr.min.js");
            public static readonly string bootstrap_datepicker_hu_min_js = Url("bootstrap-datepicker.hu.min.js");
            public static readonly string bootstrap_datepicker_hy_min_js = Url("bootstrap-datepicker.hy.min.js");
            public static readonly string bootstrap_datepicker_id_min_js = Url("bootstrap-datepicker.id.min.js");
            public static readonly string bootstrap_datepicker_is_min_js = Url("bootstrap-datepicker.is.min.js");
            public static readonly string bootstrap_datepicker_it_CH_min_js = Url("bootstrap-datepicker.it-CH.min.js");
            public static readonly string bootstrap_datepicker_it_min_js = Url("bootstrap-datepicker.it.min.js");
            public static readonly string bootstrap_datepicker_ja_min_js = Url("bootstrap-datepicker.ja.min.js");
            public static readonly string bootstrap_datepicker_ka_min_js = Url("bootstrap-datepicker.ka.min.js");
            public static readonly string bootstrap_datepicker_kh_min_js = Url("bootstrap-datepicker.kh.min.js");
            public static readonly string bootstrap_datepicker_kk_min_js = Url("bootstrap-datepicker.kk.min.js");
            public static readonly string bootstrap_datepicker_km_min_js = Url("bootstrap-datepicker.km.min.js");
            public static readonly string bootstrap_datepicker_ko_min_js = Url("bootstrap-datepicker.ko.min.js");
            public static readonly string bootstrap_datepicker_kr_min_js = Url("bootstrap-datepicker.kr.min.js");
            public static readonly string bootstrap_datepicker_lt_min_js = Url("bootstrap-datepicker.lt.min.js");
            public static readonly string bootstrap_datepicker_lv_min_js = Url("bootstrap-datepicker.lv.min.js");
            public static readonly string bootstrap_datepicker_me_min_js = Url("bootstrap-datepicker.me.min.js");
            public static readonly string bootstrap_datepicker_mk_min_js = Url("bootstrap-datepicker.mk.min.js");
            public static readonly string bootstrap_datepicker_mn_min_js = Url("bootstrap-datepicker.mn.min.js");
            public static readonly string bootstrap_datepicker_ms_min_js = Url("bootstrap-datepicker.ms.min.js");
            public static readonly string bootstrap_datepicker_nl_BE_min_js = Url("bootstrap-datepicker.nl-BE.min.js");
            public static readonly string bootstrap_datepicker_nl_min_js = Url("bootstrap-datepicker.nl.min.js");
            public static readonly string bootstrap_datepicker_no_min_js = Url("bootstrap-datepicker.no.min.js");
            public static readonly string bootstrap_datepicker_oc_min_js = Url("bootstrap-datepicker.oc.min.js");
            public static readonly string bootstrap_datepicker_pl_min_js = Url("bootstrap-datepicker.pl.min.js");
            public static readonly string bootstrap_datepicker_pt_BR_min_js = Url("bootstrap-datepicker.pt-BR.min.js");
            public static readonly string bootstrap_datepicker_pt_min_js = Url("bootstrap-datepicker.pt.min.js");
            public static readonly string bootstrap_datepicker_ro_min_js = Url("bootstrap-datepicker.ro.min.js");
            public static readonly string bootstrap_datepicker_rs_latin_min_js = Url("bootstrap-datepicker.rs-latin.min.js");
            public static readonly string bootstrap_datepicker_rs_min_js = Url("bootstrap-datepicker.rs.min.js");
            public static readonly string bootstrap_datepicker_ru_min_js = Url("bootstrap-datepicker.ru.min.js");
            public static readonly string bootstrap_datepicker_si_min_js = Url("bootstrap-datepicker.si.min.js");
            public static readonly string bootstrap_datepicker_sk_min_js = Url("bootstrap-datepicker.sk.min.js");
            public static readonly string bootstrap_datepicker_sl_min_js = Url("bootstrap-datepicker.sl.min.js");
            public static readonly string bootstrap_datepicker_sq_min_js = Url("bootstrap-datepicker.sq.min.js");
            public static readonly string bootstrap_datepicker_sr_latin_min_js = Url("bootstrap-datepicker.sr-latin.min.js");
            public static readonly string bootstrap_datepicker_sr_min_js = Url("bootstrap-datepicker.sr.min.js");
            public static readonly string bootstrap_datepicker_sv_min_js = Url("bootstrap-datepicker.sv.min.js");
            public static readonly string bootstrap_datepicker_sw_min_js = Url("bootstrap-datepicker.sw.min.js");
            public static readonly string bootstrap_datepicker_ta_min_js = Url("bootstrap-datepicker.ta.min.js");
            public static readonly string bootstrap_datepicker_tg_min_js = Url("bootstrap-datepicker.tg.min.js");
            public static readonly string bootstrap_datepicker_th_min_js = Url("bootstrap-datepicker.th.min.js");
            public static readonly string bootstrap_datepicker_tk_min_js = Url("bootstrap-datepicker.tk.min.js");
            public static readonly string bootstrap_datepicker_tr_min_js = Url("bootstrap-datepicker.tr.min.js");
            public static readonly string bootstrap_datepicker_uk_min_js = Url("bootstrap-datepicker.uk.min.js");
            public static readonly string bootstrap_datepicker_uz_cyrl_min_js = Url("bootstrap-datepicker.uz-cyrl.min.js");
            public static readonly string bootstrap_datepicker_uz_latn_min_js = Url("bootstrap-datepicker.uz-latn.min.js");
            public static readonly string bootstrap_datepicker_vi_min_js = Url("bootstrap-datepicker.vi.min.js");
            public static readonly string bootstrap_datepicker_zh_CN_min_js = Url("bootstrap-datepicker.zh-CN.min.js");
            public static readonly string bootstrap_datepicker_zh_TW_min_js = Url("bootstrap-datepicker.zh-TW.min.js");
        }
    
        public static readonly string moment_with_locales_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment-with-locales.min.js") ? Url("moment-with-locales.min.js") : Url("moment-with-locales.js");
        public static readonly string moment_with_locales_min_js = Url("moment-with-locales.min.js");
        public static readonly string moment_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment.min.js") ? Url("moment.min.js") : Url("moment.js");
        public static readonly string moment_min_js = Url("moment.min.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_matchmedia_addListener_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/respond.matchmedia.addListener.min.js") ? Url("respond.matchmedia.addListener.min.js") : Url("respond.matchmedia.addListener.js");
        public static readonly string respond_matchmedia_addListener_min_js = Url("respond.matchmedia.addListener.min.js");
        public static readonly string respond_min_js = Url("respond.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bootstrap_chosen_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-chosen.min.css") ? Url("bootstrap-chosen.min.css") : Url("bootstrap-chosen.css");
        public static readonly string bootstrap_chosen_less = Url("bootstrap-chosen.less");
        public static readonly string bootstrap_chosen_scss = Url("bootstrap-chosen.scss");
        public static readonly string bootstrap_datetimepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-datetimepicker.min.css") ? Url("bootstrap-datetimepicker.min.css") : Url("bootstrap-datetimepicker.css");
        public static readonly string bootstrap_datetimepicker_min_css = Url("bootstrap-datetimepicker.min.css");
        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
        public static readonly string bootstrap_theme_min_css_map = Url("bootstrap-theme.min.css.map");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string bootstrap_min_css_map = Url("bootstrap.min.css.map");
        public static readonly string chosen_sprite_png = Url("chosen-sprite.png");
        public static readonly string chosen_sprite_2x_png = Url("chosen-sprite@2x.png");
        public static readonly string font_awesome_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/font-awesome.min.css") ? Url("font-awesome.min.css") : Url("font-awesome.css");
        public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class locales 
            {
                public static class Assets
                {
                    public static readonly string bootstrap_datepicker_en_CA_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker-en-CA.min.js"); 
                    public static readonly string bootstrap_datepicker_ar_tn_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ar-tn.min.js"); 
                    public static readonly string bootstrap_datepicker_ar_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ar.min.js"); 
                    public static readonly string bootstrap_datepicker_az_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.az.min.js"); 
                    public static readonly string bootstrap_datepicker_bg_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.bg.min.js"); 
                    public static readonly string bootstrap_datepicker_bn_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.bn.min.js"); 
                    public static readonly string bootstrap_datepicker_br_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.br.min.js"); 
                    public static readonly string bootstrap_datepicker_bs_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.bs.min.js"); 
                    public static readonly string bootstrap_datepicker_ca_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ca.min.js"); 
                    public static readonly string bootstrap_datepicker_cs_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.cs.min.js"); 
                    public static readonly string bootstrap_datepicker_cy_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.cy.min.js"); 
                    public static readonly string bootstrap_datepicker_da_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.da.min.js"); 
                    public static readonly string bootstrap_datepicker_de_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.de.min.js"); 
                    public static readonly string bootstrap_datepicker_el_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.el.min.js"); 
                    public static readonly string bootstrap_datepicker_en_AU_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.en-AU.min.js"); 
                    public static readonly string bootstrap_datepicker_en_CA_min_js_ = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.en-CA.min.js"); 
                    public static readonly string bootstrap_datepicker_en_GB_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.en-GB.min.js"); 
                    public static readonly string bootstrap_datepicker_en_IE_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.en-IE.min.js"); 
                    public static readonly string bootstrap_datepicker_en_NZ_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.en-NZ.min.js"); 
                    public static readonly string bootstrap_datepicker_en_ZA_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.en-ZA.min.js"); 
                    public static readonly string bootstrap_datepicker_eo_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.eo.min.js"); 
                    public static readonly string bootstrap_datepicker_es_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.es.min.js"); 
                    public static readonly string bootstrap_datepicker_et_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.et.min.js"); 
                    public static readonly string bootstrap_datepicker_eu_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.eu.min.js"); 
                    public static readonly string bootstrap_datepicker_fa_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.fa.min.js"); 
                    public static readonly string bootstrap_datepicker_fi_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.fi.min.js"); 
                    public static readonly string bootstrap_datepicker_fo_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.fo.min.js"); 
                    public static readonly string bootstrap_datepicker_fr_CH_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.fr-CH.min.js"); 
                    public static readonly string bootstrap_datepicker_fr_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.fr.min.js"); 
                    public static readonly string bootstrap_datepicker_gl_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.gl.min.js"); 
                    public static readonly string bootstrap_datepicker_he_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.he.min.js"); 
                    public static readonly string bootstrap_datepicker_hi_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.hi.min.js"); 
                    public static readonly string bootstrap_datepicker_hr_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.hr.min.js"); 
                    public static readonly string bootstrap_datepicker_hu_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.hu.min.js"); 
                    public static readonly string bootstrap_datepicker_hy_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.hy.min.js"); 
                    public static readonly string bootstrap_datepicker_id_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.id.min.js"); 
                    public static readonly string bootstrap_datepicker_is_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.is.min.js"); 
                    public static readonly string bootstrap_datepicker_it_CH_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.it-CH.min.js"); 
                    public static readonly string bootstrap_datepicker_it_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.it.min.js"); 
                    public static readonly string bootstrap_datepicker_ja_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ja.min.js"); 
                    public static readonly string bootstrap_datepicker_ka_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ka.min.js"); 
                    public static readonly string bootstrap_datepicker_kh_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.kh.min.js"); 
                    public static readonly string bootstrap_datepicker_kk_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.kk.min.js"); 
                    public static readonly string bootstrap_datepicker_km_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.km.min.js"); 
                    public static readonly string bootstrap_datepicker_ko_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ko.min.js"); 
                    public static readonly string bootstrap_datepicker_kr_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.kr.min.js"); 
                    public static readonly string bootstrap_datepicker_lt_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.lt.min.js"); 
                    public static readonly string bootstrap_datepicker_lv_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.lv.min.js"); 
                    public static readonly string bootstrap_datepicker_me_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.me.min.js"); 
                    public static readonly string bootstrap_datepicker_mk_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.mk.min.js"); 
                    public static readonly string bootstrap_datepicker_mn_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.mn.min.js"); 
                    public static readonly string bootstrap_datepicker_ms_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ms.min.js"); 
                    public static readonly string bootstrap_datepicker_nl_BE_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.nl-BE.min.js"); 
                    public static readonly string bootstrap_datepicker_nl_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.nl.min.js"); 
                    public static readonly string bootstrap_datepicker_no_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.no.min.js"); 
                    public static readonly string bootstrap_datepicker_oc_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.oc.min.js"); 
                    public static readonly string bootstrap_datepicker_pl_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.pl.min.js"); 
                    public static readonly string bootstrap_datepicker_pt_BR_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.pt-BR.min.js"); 
                    public static readonly string bootstrap_datepicker_pt_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.pt.min.js"); 
                    public static readonly string bootstrap_datepicker_ro_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ro.min.js"); 
                    public static readonly string bootstrap_datepicker_rs_latin_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.rs-latin.min.js"); 
                    public static readonly string bootstrap_datepicker_rs_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.rs.min.js"); 
                    public static readonly string bootstrap_datepicker_ru_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ru.min.js"); 
                    public static readonly string bootstrap_datepicker_si_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.si.min.js"); 
                    public static readonly string bootstrap_datepicker_sk_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.sk.min.js"); 
                    public static readonly string bootstrap_datepicker_sl_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.sl.min.js"); 
                    public static readonly string bootstrap_datepicker_sq_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.sq.min.js"); 
                    public static readonly string bootstrap_datepicker_sr_latin_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.sr-latin.min.js"); 
                    public static readonly string bootstrap_datepicker_sr_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.sr.min.js"); 
                    public static readonly string bootstrap_datepicker_sv_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.sv.min.js"); 
                    public static readonly string bootstrap_datepicker_sw_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.sw.min.js"); 
                    public static readonly string bootstrap_datepicker_ta_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.ta.min.js"); 
                    public static readonly string bootstrap_datepicker_tg_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.tg.min.js"); 
                    public static readonly string bootstrap_datepicker_th_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.th.min.js"); 
                    public static readonly string bootstrap_datepicker_tk_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.tk.min.js"); 
                    public static readonly string bootstrap_datepicker_tr_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.tr.min.js"); 
                    public static readonly string bootstrap_datepicker_uk_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.uk.min.js"); 
                    public static readonly string bootstrap_datepicker_uz_cyrl_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.uz-cyrl.min.js"); 
                    public static readonly string bootstrap_datepicker_uz_latn_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.uz-latn.min.js"); 
                    public static readonly string bootstrap_datepicker_vi_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.vi.min.js"); 
                    public static readonly string bootstrap_datepicker_zh_CN_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.zh-CN.min.js"); 
                    public static readonly string bootstrap_datepicker_zh_TW_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/locales/bootstrap-datepicker.zh-TW.min.js"); 
                }
            }
            public static class Assets
            {
                public static readonly string bootbox_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootbox.js"); 
                public static readonly string bootbox_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootbox.min.js"); 
                public static readonly string bootstrap_datepicker_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-datepicker.js"); 
                public static readonly string bootstrap_datepicker_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-datepicker.min.js"); 
                public static readonly string bootstrap_datetimepicker_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-datetimepicker.js"); 
                public static readonly string bootstrap_datetimepicker_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap-datetimepicker.min.js"); 
                public static readonly string bootstrap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.js"); 
                public static readonly string bootstrap_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/bootstrap.min.js"); 
                public static readonly string chosen_jquery_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/chosen.jquery.js"); 
                public static readonly string chosen_jquery_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/chosen.jquery.min.js"); 
                public static readonly string jquery_1_12_4_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.12.4.js"); 
                public static readonly string jquery_1_12_4_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-1.12.4.min.js"); 
                public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.unobtrusive-ajax.js"); 
                public static readonly string jquery_unobtrusive_ajax_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.unobtrusive-ajax.min.js"); 
                public static readonly string jquery_validate_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.js"); 
                public static readonly string jquery_validate_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.min.js"); 
                public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.js"); 
                public static readonly string jquery_validate_unobtrusive_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.validate.unobtrusive.min.js"); 
                public static readonly string moment_with_locales_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment-with-locales.js"); 
                public static readonly string moment_with_locales_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment-with-locales.min.js"); 
                public static readonly string moment_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment.js"); 
                public static readonly string moment_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment.min.js"); 
                public static readonly string respond_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/respond.js"); 
                public static readonly string respond_matchmedia_addListener_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/respond.matchmedia.addListener.js"); 
                public static readonly string respond_matchmedia_addListener_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/respond.matchmedia.addListener.min.js"); 
                public static readonly string respond_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/respond.min.js"); 
            }
        }
        public static partial class Content 
        {
            public static class Assets
            {
                public static readonly string bootstrap_chosen_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-chosen.css");
                public static readonly string bootstrap_datetimepicker_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-datetimepicker.css");
                public static readonly string bootstrap_datetimepicker_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-datetimepicker.min.css");
                public static readonly string bootstrap_theme_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-theme.css");
                public static readonly string bootstrap_theme_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap-theme.min.css");
                public static readonly string bootstrap_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.css");
                public static readonly string bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.min.css");
                public static readonly string font_awesome_css = T4MVCHelpers.ProcessAssetPath("~/Content/font-awesome.css");
                public static readonly string font_awesome_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/font-awesome.min.css");
                public static readonly string Site_css = T4MVCHelpers.ProcessAssetPath("~/Content/Site.css");
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


