//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementMeetingsTracker.BE
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingItem
    {
        public int MeetingItemId { get; set; }
        public int MeetingId { get; set; }
        public string ActionBy { get; set; }
        public int MeetingItemStatusId { get; set; }
        public string MeetingItem1 { get; set; }
        public string Remark { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual MeetingItemStatu MeetingItemStatu { get; set; }
    }
}
